"""Run and score a large p=0.2% Gross144 campaign on the four-lane FPGA.

The programmed image is basis-specific. Every detector shot is generated by
the pinned Relay/Stim circuit, decoded on board, and scored against Stim's 12
actual observable bits. Wrong words, defers, decoder errors, timeouts, and
transport corruption are all release failures.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import statistics
import subprocess
import sys
import time
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

BOARD_CLOCK = json.loads((ROOT / "config" / "board_clock.json").read_text(encoding="utf-8"))

from mitten.paper_gross144 import (  # noqa: E402
    PaperGross144Stage1Config,
    PaperGross144Stage1FpgaAdapter,
    WideMinSumRescueProfile,
)
from mitten.paper_gross144_cpu_telescope import (  # noqa: E402
    CpuTelescopeConfig,
    PaperGross144CpuTelescope,
)
from mitten.protocol import Frame, FrameParser, encode_frame  # noqa: E402
from mitten.wide_minsum import GROSS144_FOUR_LANE_PAIR_GROUPS  # noqa: E402

COMMAND = 0x31
DEFAULT_CORE_CLOCK_HZ = float(BOARD_CLOCK["core_clock_hz"])


def _profiles() -> tuple[WideMinSumRescueProfile, ...]:
    return (
        WideMinSumRescueProfile("S1WT_C", 3, 6, 4, 30,
                                check_schedule="four_lane_pair_alternating"),
        WideMinSumRescueProfile("S1WT_D", 3, 6, 4, 20,
                                check_schedule="four_lane_pair_alternating_reverse"),
        WideMinSumRescueProfile(
            "S1WT_E3", 2, 5, 3, 32,
            check_schedule="four_lane_pair_cyclic_alternating", schedule_stride=216,
        ),
        WideMinSumRescueProfile("S1WT_F", 3, 6, 4, 28,
                                check_schedule="four_lane_pair_alternating_reverse"),
        WideMinSumRescueProfile(
            "S1WT_G", 2, 6, 4, 28,
            check_schedule="four_lane_pair_cyclic_alternating_reverse", schedule_stride=144,
        ),
        WideMinSumRescueProfile("S1WT_H", 2, 6, 4, 28,
                                check_schedule="four_lane_pair_alternating_reverse"),
    )


def _pack_groups(syndrome: np.ndarray) -> bytes:
    if syndrome.shape != (936,):
        raise ValueError(f"expected 936 detector bits, got {syndrome.shape}")
    payload = bytearray(117)
    ordinal = 0
    for time_index in range(13):
        for group in GROSS144_FOUR_LANE_PAIR_GROUPS:
            word = 0
            for lane, coordinate in enumerate(group):
                word |= int(syndrome[time_index * 72 + coordinate]) << lane
            payload[ordinal >> 1] |= word << (4 * (ordinal & 1))
            ordinal += 1
    return bytes(payload)


def _word(bits: np.ndarray) -> int:
    return sum(int(value) << index for index, value in enumerate(bits))


def _one_sided_upper95(failures: int, shots: int) -> float:
    if not shots:
        return 1.0
    if failures == shots:
        return 1.0
    if failures == 0:
        return 1.0 - 0.05 ** (1.0 / shots)
    from scipy.stats import beta
    return float(beta.ppf(0.95, failures + 1, shots - failures))


def _two_sided_upper95(failures: int, shots: int) -> float:
    if not shots:
        return 1.0
    if failures == 0:
        return 1.0 - 0.025 ** (1.0 / shots)
    from scipy.stats import beta
    return float(beta.ppf(0.975, failures + 1, shots - failures))


def _git_provenance() -> tuple[str, bool]:
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, check=True,
            capture_output=True, text=True,
        ).stdout.strip()
        dirty = bool(subprocess.run(
            ["git", "status", "--porcelain"], cwd=ROOT, check=True,
            capture_output=True, text=True,
        ).stdout.strip())
        return commit, dirty
    except (OSError, subprocess.CalledProcessError):
        return "unknown", True


class Board:
    def __init__(self, port: str, baud: int, timeout: float):
        import serial  # type: ignore
        self.serial = serial.Serial(
            port=port, baudrate=baud, bytesize=serial.EIGHTBITS,
            parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE,
            timeout=0.01, write_timeout=1.0,
        )
        self.timeout = timeout
        self.sequence = 1
        self.parser = FrameParser(max_payload=117)

    def close(self) -> None:
        self.serial.close()

    def decode(self, syndrome: np.ndarray) -> dict[str, int | float | bool]:
        sequence = self.sequence
        self.sequence = 1 if sequence == 0xFFFF else sequence + 1
        request = encode_frame(Frame(COMMAND, sequence, _pack_groups(syndrome)))
        start = time.perf_counter_ns()
        self.serial.write(request)
        self.serial.flush()
        deadline = time.monotonic() + self.timeout
        while time.monotonic() < deadline:
            chunk = self.serial.read(max(1, self.serial.in_waiting))
            if not chunk:
                continue
            for frame in self.parser.feed(chunk):
                if frame.sequence != sequence:
                    continue
                if frame.command != (COMMAND | 0x80):
                    raise RuntimeError(f"unexpected response command 0x{frame.command:02x}")
                if len(frame.payload) != 11:
                    raise RuntimeError(f"unexpected response length {len(frame.payload)}")
                status = frame.payload[0]
                return {
                    "success": bool(status & 0x01),
                    "deferred": bool(status & 0x02),
                    "error": bool(status & 0x04),
                    "basis_id": frame.payload[10],
                    "profile": frame.payload[1] & 0x07,
                    "logical": (frame.payload[2] & 0x0F) | (frame.payload[3] << 4),
                    "cycles": int.from_bytes(frame.payload[4:8], "little"),
                    "sweeps": int.from_bytes(frame.payload[8:10], "little"),
                    "wall_ns": time.perf_counter_ns() - start,
                }
        raise TimeoutError(f"timeout waiting for sequence {sequence}")


def _args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", required=True)
    parser.add_argument("--basis", choices=("X", "Z"), required=True)
    parser.add_argument("--shots", type=int, default=300_000)
    parser.add_argument("--seed", type=int, default=260_813_002)
    parser.add_argument("--batch-size", type=int, default=2048)
    parser.add_argument("--baud", type=int, default=3_000_000)
    parser.add_argument(
        "--core-clock-hz", type=float, default=DEFAULT_CORE_CLOCK_HZ,
        help="production clock from config/board_clock.json used for cycle conversion",
    )
    parser.add_argument("--timeout", type=float, default=0.25)
    parser.add_argument("--relay-root", type=Path, default=ROOT / "build" / "relay")
    parser.add_argument("--bitstream", type=Path)
    parser.add_argument("--failure-case-limit", type=int, default=32)
    parser.add_argument(
        "--cpu-telescope-handoff",
        dest="cpu_telescope_handoff", action="store_true",
        help="route FPGA deferred results to the resident host C telescope",
    )
    parser.add_argument(
        "--cpu-backend",
        choices=("c",),
        default="c",
        help="production resident C Relay tail (the only supported backend)",
    )
    parser.add_argument(
        "--fast-first", action=argparse.BooleanOptionalAction, default=True,
        help="use the verified speculative config-0 C-tail shortcut (default: on)",
    )
    parser.add_argument(
        "--smoke", action="store_true",
        help="require exact functional/transport success without the large-shot CI gate",
    )
    parser.add_argument(
        "--deferred-corpus", type=Path,
        help="optionally save full detector words for FPGA-deferred shots as an NPZ corpus",
    )
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = _args()
    if args.shots < 1 or args.batch_size < 1 or args.timeout <= 0 or args.core_clock_hz <= 0:
        raise SystemExit("shots, batch-size, timeout, and core-clock-hz must be positive")
    if args.deferred_corpus is not None and not args.cpu_telescope_handoff:
        raise SystemExit("--deferred-corpus requires --cpu-telescope-handoff")
    expected_basis_id = 0 if args.basis == "X" else 1
    adapter = PaperGross144Stage1FpgaAdapter(
        args.relay_root,
        config=PaperGross144Stage1Config(
            physical_error_rate=0.002, minsum_iterations=10, llr_scale=4,
            message_magnitude_bits=5, normalization_correction_shift=3,
            check_schedule="four_lane_pair_alternating_reverse",
            wide_rescue_profiles=_profiles(),
        ),
    )
    layout = adapter.layouts[args.basis]
    cpu_telescope: PaperGross144CpuTelescope | None = None
    if args.cpu_telescope_handoff:
        # The FPGA receives the exact basis-filtered projection, while the
        # host retains the full correlated detector word needed by the rare
        # CPU telescope. This avoids a second 1,728-bit UART transfer on every
        # deferred shot and keeps the common case entirely on the FPGA.
        cpu_telescope = PaperGross144CpuTelescope(
            args.relay_root, p=0.002, basis=args.basis,
            config=CpuTelescopeConfig(
                backend=args.cpu_backend, c_relay_fast_first=args.fast_first,
            ),
        )
        full_layout = cpu_telescope.layout
        sampler = full_layout.circuit.compile_detector_sampler(
            seed=args.seed,
        )
        selected_detector_indices = np.asarray(
            layout.selected_detector_indices, dtype=np.intp,
        )
    else:
        full_layout = None
        s2_image = None
        selected_detector_indices = None
        sampler = layout.circuit.compile_detector_sampler(seed=args.seed)
    board = Board(args.port, args.baud, args.timeout)
    cycles: list[int] = []
    wall_ns: list[int] = []
    endpoint_core_ns: list[int] = []
    endpoint_wall_ns: list[int] = []
    cpu_telescope_ns: list[int] = []
    cpu_portfolio_ns: list[int] = []
    cpu_selection_ns: list[int] = []
    cpu_relay_primary_ns: list[int] = []
    cpu_relay_escape_ns: list[int] = []
    cpu_relay_sets: list[int] = []
    cpu_relay_stages: list[int] = []
    cpu_relay_disagreements: list[int] = []
    deferred_syndromes: list[np.ndarray] = []
    deferred_actual: list[np.ndarray] = []
    cpu_telescope_backends = Counter()
    sweeps = Counter()
    profiles = Counter()
    failures: list[dict[str, object]] = []
    counters = Counter()
    started = time.perf_counter()
    try:
        while counters["shots"] < args.shots:
            take = min(args.batch_size, args.shots - counters["shots"])
            detector_batch, actual_batch = sampler.sample(
                take, separate_observables=True,
            )
            for local_index in range(take):
                full_syndrome = np.asarray(
                    detector_batch[local_index], dtype=np.uint8,
                )
                syndrome = (
                    full_syndrome[selected_detector_indices]
                    if args.cpu_telescope_handoff else full_syndrome
                )
                actual = _word(np.asarray(actual_batch[local_index], dtype=np.uint8))
                index = counters["shots"]
                transport_error: str | None = None
                try:
                    fpga_result = board.decode(syndrome)
                except Exception as exc:
                    fpga_result = {"success": False, "deferred": False, "error": True,
                              "logical": -1, "cycles": 0, "sweeps": 0,
                              "profile": 0, "basis_id": -1, "wall_ns": 0}
                    transport_error = (
                        f"{type(exc).__name__}: {exc}; "
                        f"parser_crc={board.parser.crc_errors}; "
                        f"parser_format={board.parser.format_errors}"
                    )
                    counters["transport_errors"] += 1
                if transport_error is None and fpga_result["basis_id"] != expected_basis_id:
                    raise RuntimeError(
                        f"programmed FPGA basis mismatch: requested {args.basis} "
                        f"(id {expected_basis_id}), received id {fpga_result['basis_id']}; "
                        "flash the matching production bitstream before benchmarking"
                    )
                result = fpga_result
                cpu_telescope_summary: dict[str, object] | None = None
                endpoint_success = bool(fpga_result["success"])
                endpoint_logical = int(fpga_result["logical"])
                endpoint_core = int(
                    round(int(fpga_result["cycles"]) / args.core_clock_hz * 1e9)
                )
                endpoint_wall = int(fpga_result["wall_ns"])
                if args.cpu_telescope_handoff and fpga_result["deferred"] and \
                        transport_error is None:
                    if args.deferred_corpus is not None:
                        deferred_syndromes.append(full_syndrome.copy())
                        deferred_actual.append(
                            np.asarray(actual_batch[local_index], dtype=np.uint8).copy()
                        )
                    counters["cpu_telescope_handoff"] += 1
                    try:
                        tail = cpu_telescope.decode(full_syndrome)
                        endpoint_success = bool(tail.accepted)
                        endpoint_logical = _word(np.asarray(
                            tail.predicted_logicals, dtype=np.uint8,
                        ))
                        cpu_telescope_ns.append(tail.wall_ns)
                        cpu_portfolio_ns.append(int(tail.portfolio_ns))
                        cpu_selection_ns.append(int(tail.selection_ns))
                        cpu_relay_primary_ns.append(int(tail.relay_primary_ns))
                        cpu_relay_escape_ns.append(int(tail.relay_escape_ns))
                        cpu_relay_sets.append(int(tail.relay_sets_attempted))
                        cpu_relay_stages.append(int(tail.relay_stage_reached))
                        cpu_relay_disagreements.append(int(tail.logical_disagreement))
                        endpoint_core += tail.wall_ns
                        endpoint_wall += tail.wall_ns
                        cpu_telescope_backends[tail.backend] += 1
                        counters[f"cpu_telescope_{tail.backend}"] += 1
                        counters["cpu_telescope_accepted"] += int(tail.accepted)
                        counters["cpu_telescope_rejected"] += int(not tail.accepted)
                        counters["cpu_telescope_syndrome_mismatch"] += int(
                            not tail.syndrome_exact
                        )
                        cpu_telescope_summary = {
                        "accepted": bool(tail.accepted),
                        "logical": endpoint_logical,
                        "syndrome_exact": bool(tail.syndrome_exact),
                        "backend": tail.backend,
                        "stage": tail.stage,
                        "iterations": int(tail.iterations),
                        "candidate_count": int(tail.candidate_count),
                        "reason": tail.reason,
                        "wall_ns": int(tail.wall_ns),
                        }
                    except Exception as exc:
                        counters["cpu_telescope_errors"] += 1
                        endpoint_success = False
                        cpu_telescope_summary = {
                            "accepted": False,
                            "backend": cpu_telescope.backend,
                            "stage": "HOST_RELAY_ERROR",
                            "reason": f"{type(exc).__name__}: {exc}",
                        }
                counters["shots"] += 1
                cycles.append(int(fpga_result["cycles"]))
                wall_ns.append(int(fpga_result["wall_ns"]))
                endpoint_core_ns.append(endpoint_core)
                endpoint_wall_ns.append(endpoint_wall)
                sweeps[int(fpga_result["sweeps"])] += 1
                profiles[int(fpga_result["profile"])] += 1
                if fpga_result["deferred"]:
                    counters["deferred"] += 1
                if fpga_result["error"]:
                    counters["decoder_errors"] += 1
                if fpga_result["basis_id"] != expected_basis_id:
                    counters["basis_mismatches"] += 1
                fpga_wrong = int(fpga_result["logical"]) != actual
                wrong = endpoint_logical != actual
                if fpga_wrong:
                    counters["fpga_wrong_logical"] += 1
                if wrong:
                    counters["wrong_logical"] += 1
                fpga_failed = (
                    transport_error is not None or not fpga_result["success"] or
                    fpga_result["deferred"] or fpga_result["error"] or fpga_wrong or
                    fpga_result["basis_id"] != expected_basis_id
                )
                if fpga_failed:
                    counters["fpga_failures"] += 1
                failed = (transport_error is not None or not endpoint_success or
                          (fpga_result["deferred"] and not args.cpu_telescope_handoff) or
                          fpga_result["error"] or wrong or
                          fpga_result["basis_id"] != expected_basis_id)
                if failed:
                    counters["failures"] += 1
                    if counters["failures"] <= 8:
                        print(json.dumps({
                            "event": "live_failure",
                            "index": index,
                            "transport_error": transport_error,
                            "fpga": fpga_result,
                            "cpu_telescope": cpu_telescope_summary,
                            "endpoint": {
                                "success": endpoint_success,
                                "logical": endpoint_logical,
                            },
                        }, sort_keys=True), flush=True)
                    if len(failures) < args.failure_case_limit:
                        failures.append({
                            "index": index, "actual_logical": actual,
                            "fpga": fpga_result,
                            "cpu_telescope": cpu_telescope_summary,
                            "endpoint": {
                                "success": endpoint_success,
                                "logical": endpoint_logical,
                                "core_ns": endpoint_core,
                                "wall_ns": endpoint_wall,
                            },
                            "transport_error": transport_error,
                            "syndrome_hex": np.packbits(
                                full_syndrome, bitorder="little",
                            ).tobytes().hex(),
                        })
            elapsed = time.perf_counter() - started
            rate = counters["shots"] / elapsed
            print(
                f"{args.basis} shots={counters['shots']}/{args.shots} "
                f"fail={counters['failures']} mean_us="
                f"{statistics.fmean(cycles) / args.core_clock_hz * 1e6:.3f} "
                f"rate={rate:.1f}/s",
                flush=True,
            )
    finally:
        board.close()
        if cpu_telescope is not None:
            cpu_telescope.close()

    elapsed = time.perf_counter() - started
    shots = counters["shots"]
    failure_count = counters["failures"]
    mean_cycles = statistics.fmean(cycles)
    ordered_cycles = sorted(cycles)
    ordered_wall = sorted(wall_ns)
    ordered_endpoint_core = sorted(endpoint_core_ns)
    ordered_endpoint_wall = sorted(endpoint_wall_ns)
    ordered_cpu_telescope = sorted(cpu_telescope_ns)
    ordered_cpu_portfolio = sorted(cpu_portfolio_ns)
    ordered_cpu_selection = sorted(cpu_selection_ns)
    ordered_cpu_relay_primary = sorted(cpu_relay_primary_ns)
    ordered_cpu_relay_escape = sorted(cpu_relay_escape_ns)
    percentile = lambda values, q: values[min(len(values) - 1, math.ceil(q * len(values)) - 1)]
    phase_stats = {}
    for name, values, ordered in (
        ("portfolio", cpu_portfolio_ns, ordered_cpu_portfolio),
        ("selection", cpu_selection_ns, ordered_cpu_selection),
        ("relay_primary", cpu_relay_primary_ns, ordered_cpu_relay_primary),
        ("relay_escape", cpu_relay_escape_ns, ordered_cpu_relay_escape),
    ):
        phase_stats[name] = {
            "mean_us": statistics.fmean(values) / 1e3 if values else 0.0,
            "p99_us": percentile(ordered, 0.99) / 1e3 if values else 0.0,
        }
    git_commit, git_dirty = _git_provenance()
    endpoint_mean_core_us = statistics.fmean(endpoint_core_ns) / 1e3
    endpoint_mean_wall_us = statistics.fmean(endpoint_wall_ns) / 1e3
    payload: dict[str, object] = {
        "schema": "PAPER_GROSS144_FOUR_LANE_BOARD_CAMPAIGN_V3",
        "timestamp_utc": datetime.now(UTC).isoformat(),
        "basis": args.basis,
        "p": 0.002,
        "shots": shots,
        "seed": args.seed,
        "git_commit": git_commit,
        "git_dirty": git_dirty,
        "configuration_sha256": hashlib.sha256(
            (adapter.configuration_sha256 + ":" + (
                cpu_telescope.configuration_sha256
                if cpu_telescope is not None else "none"
            )).encode("ascii")
        ).hexdigest(),
        "fpga_configuration_sha256": adapter.configuration_sha256,
        "cpu_telescope_configuration_sha256": (
            cpu_telescope.configuration_sha256
            if cpu_telescope is not None else None
        ),
        "c_tail_source_sha256": (
            cpu_telescope.c_tail_source_sha256
            if cpu_telescope is not None else None
        ),
        "c_tail_image_sha256": (
            cpu_telescope.c_tail_image_sha256
            if cpu_telescope is not None else None
        ),
        "c_tail_binary_sha256": (
            cpu_telescope.c_tail_binary_sha256
            if cpu_telescope is not None else None
        ),
        "c_tail_image_manifest_sha256": (
            cpu_telescope.c_tail_image_manifest_sha256
            if cpu_telescope is not None else None
        ),
        "core_cycles": mean_cycles,
        "fpga_clock_hz": args.core_clock_hz,
        "core_clock_hz": args.core_clock_hz,
        "core_latency_us": mean_cycles / args.core_clock_hz * 1e6,
        "baud": args.baud,
        "counters": dict(counters),
        "fpga_block_ler": counters["fpga_failures"] / shots,
        "fpga_block_ler_upper95_one_sided": _one_sided_upper95(
            counters["fpga_failures"], shots,
        ),
        "block_ler": failure_count / shots,
        "block_ler_upper95_one_sided": _one_sided_upper95(failure_count, shots),
        "block_ler_upper95_two_sided": _two_sided_upper95(failure_count, shots),
        "mean_core_cycles": mean_cycles,
        "mean_core_latency_us": mean_cycles / args.core_clock_hz * 1e6,
        "p50_core_latency_us": percentile(ordered_cycles, 0.50) / args.core_clock_hz * 1e6,
        "p99_core_latency_us": percentile(ordered_cycles, 0.99) / args.core_clock_hz * 1e6,
        "max_core_latency_us": max(cycles) / args.core_clock_hz * 1e6,
        "mean_wall_latency_us": statistics.fmean(wall_ns) / 1e3,
        "p99_wall_latency_us": percentile(ordered_wall, 0.99) / 1e3,
        "cpu_telescope_handoff": bool(args.cpu_telescope_handoff),
        "cpu_telescope_backend": (
            cpu_telescope.backend if cpu_telescope is not None else None
        ),
        "cpu_telescope_fast_first": bool(args.fast_first),
        "cpu_telescope_backends": dict(sorted(cpu_telescope_backends.items())),
        "cpu_telescope_handoff_shots": len(cpu_telescope_ns),
        "mean_cpu_telescope_handoff_us": (
            statistics.fmean(cpu_telescope_ns) / 1e3
            if cpu_telescope_ns else 0.0
        ),
        "p99_cpu_telescope_handoff_us": (
            percentile(ordered_cpu_telescope, 0.99) / 1e3
            if cpu_telescope_ns else 0.0
        ),
        "cpu_telescope_phase_latency": phase_stats,
        "cpu_telescope_relay_sets_mean": (
            statistics.fmean(cpu_relay_sets) if cpu_relay_sets else 0.0
        ),
        "cpu_telescope_relay_sets_max": max(cpu_relay_sets) if cpu_relay_sets else 0,
        "cpu_telescope_relay_stage_histogram": dict(sorted(Counter(cpu_relay_stages).items())),
        "cpu_telescope_logical_disagreement_count": sum(cpu_relay_disagreements),
        "mean_endpoint_core_latency_us": endpoint_mean_core_us,
        "p99_endpoint_core_latency_us": percentile(ordered_endpoint_core, 0.99) / 1e3,
        "max_endpoint_core_latency_us": max(endpoint_core_ns) / 1e3,
        "mean_endpoint_wall_latency_us": endpoint_mean_wall_us,
        "p99_endpoint_wall_latency_us": percentile(ordered_endpoint_wall, 0.99) / 1e3,
        "elapsed_seconds": elapsed,
        "shots_per_second": shots / elapsed,
        "sweep_histogram": dict(sorted(sweeps.items())),
        "profile_histogram": dict(sorted(profiles.items())),
        "parser_crc_errors": board.parser.crc_errors,
        "parser_format_errors": board.parser.format_errors,
        "failure_cases": failures,
        "deferred_corpus": (
            str(args.deferred_corpus.resolve()) if args.deferred_corpus else None
        ),
        "deferred_corpus_shots": len(deferred_syndromes),
        # Compatibility aliases for older report consumers.
        "cpu_s2_handoff": bool(args.cpu_telescope_handoff),
        "cpu_s2_handoff_shots": len(cpu_telescope_ns),
        "mean_cpu_s2_handoff_us": (
            statistics.fmean(cpu_telescope_ns) / 1e3
            if cpu_telescope_ns else 0.0
        ),
        "p99_cpu_s2_handoff_us": (
            percentile(ordered_cpu_telescope, 0.99) / 1e3
            if cpu_telescope_ns else 0.0
        ),
        "bitstream": (str(args.bitstream.resolve()) if args.bitstream else None),
        "bitstream_sha256": (
            hashlib.sha256(args.bitstream.read_bytes()).hexdigest()
            if args.bitstream else None
        ),
    }
    payload["transport_pass"] = bool(
        counters["transport_errors"] == 0 and counters["decoder_errors"] == 0 and
        counters["basis_mismatches"] == 0 and
        board.parser.crc_errors == 0 and board.parser.format_errors == 0
    )
    payload["functional_pass"] = bool(
        failure_count == 0 and payload["transport_pass"]
    )
    payload["endpoint_pass"] = bool(
        payload["block_ler_upper95_one_sided"] <= 1e-5 and
        endpoint_mean_core_us <= 1000.0 and payload["transport_pass"]
    )
    if args.deferred_corpus is not None:
        args.deferred_corpus.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            args.deferred_corpus,
            detectors=(
                np.asarray(deferred_syndromes, dtype=np.uint8)
                if deferred_syndromes else np.empty((0, full_layout.checks), dtype=np.uint8)
            ),
            actual_logicals=(
                np.asarray(deferred_actual, dtype=np.uint8)
                if deferred_actual else np.empty((0, 12), dtype=np.uint8)
            ),
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: payload[key] for key in (
        "basis", "shots", "block_ler", "block_ler_upper95_one_sided",
        "mean_core_latency_us", "mean_endpoint_core_latency_us",
        "mean_cpu_telescope_handoff_us", "cpu_telescope_backend",
        "endpoint_pass",
    )}, indent=2))
    return 0 if (payload["functional_pass"] if args.smoke else
                 payload["endpoint_pass"]) else 1


if __name__ == "__main__":
    raise SystemExit(main())
